apiVersion: v1
kind: Service
metadata:
  name: vllm-service
  namespace: default
  labels:
    app: vllm-inference
spec:
  type: LoadBalancer
  selector:
    app: vllm-inference
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: api
